import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

// Modules
import {
    MatAutocompleteModule,
    MatExpansionModule,
    MatButtonModule,
    MatFormFieldModule,
    MatIconModule,
    MatMenuModule,
    MatSelectModule,
    MatTabsModule,
    MatInputModule,
    MatCardModule,
    MatPaginatorModule,
    MatTableModule,
    MatCheckboxModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatChipsModule,
    MatSortModule,
    MatOptionModule,
    MatRadioModule,
    MatDividerModule,
    MatProgressBarModule,
    MatListModule,
    MatSlideToggleModule,

} from '@angular/material';


@NgModule({
    imports: [
        MatAutocompleteModule,
        MatExpansionModule,
        MatButtonModule,
        MatFormFieldModule,
        MatIconModule,
        MatMenuModule,
        MatSelectModule,
        MatTabsModule,
        MatInputModule,
        MatCardModule,
        MatPaginatorModule,
        MatTableModule,
        MatCheckboxModule,
        MatTooltipModule,
        MatProgressSpinnerModule,
        MatDialogModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatChipsModule,
        MatSortModule,
        MatOptionModule,
        CommonModule,
        MatRadioModule,
        MatDividerModule,
        MatProgressBarModule,
        MatListModule,
        MatSlideToggleModule,
    ],
    exports: [
        MatAutocompleteModule,
        MatExpansionModule,
        MatButtonModule,
        MatFormFieldModule,
        MatIconModule,
        MatMenuModule,
        MatSelectModule,
        MatTabsModule,
        MatInputModule,
        MatCardModule,
        MatPaginatorModule,
        MatTableModule,
        MatCheckboxModule,
        MatTooltipModule,
        MatProgressSpinnerModule,
        MatDialogModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatChipsModule,
        MatSortModule,
        MatOptionModule,
        CommonModule,
        MatRadioModule,
        MatDividerModule,
        MatProgressBarModule,
        MatListModule,
        MatSlideToggleModule,
    ],

})
export class MaterialModule { }